version: '3.9'

services:
  web:
    build:
      context: ./djangoProject
      dockerfile: Dockerfile
    container_name: drf_web
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - ./djangoProject:/app  
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: drf_db
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: